name: fluid-styled-content/menu-pages
typeName: menu_pages
group: menu
prefixFields: false
basics:
  - FluidStyledContent/Appearance
  - FluidStyledContent/Links
  - FluidStyledContent/Categories
fields:
  - identifier: FluidStyledContent/Headers
    type: Basic
  - identifier: pages
    useExistingField: true
