name: fluid-styled-content/table
typeName: table
group: lists
prefixFields: false
basics:
  - FluidStyledContent/Categories
fields:
  - identifier: FluidStyledContent/Headers
    type: Basic
  - identifier: bodytext
    useExistingField: true
    renderType: textTable
    wrap: off
  - identifier: table_configuration_palette
    type: Palette
    fields:
      - identifier: table_delimiter
        type: SelectNumber
        default: 124
        items:
          - value: 124
          - value: 59
          - value: 58
          - value: 44
          - value: 9
      - identifier: table_enclosure
        type: SelectNumber
        default: 0
        items:
          - value: 0
          - value: 39
          - value: 34
  - identifier: table_caption
    type: Text
  - identifier: FluidStyledContent/Appearance
    type: Basic
  - identifier: table_layout_palette
    type: Palette
    fields:
      - identifier: cols
        type: SelectNumber
        default: 0
        items:
          - value: 0
          - label: '1'
            value: 1
          - label: '2'
            value: 2
          - label: '3'
            value: 3
          - label: '4'
            value: 4
          - label: '5'
            value: 5
          - label: '6'
            value: 6
          - label: '7'
            value: 7
          - label: '8'
            value: 8
          - label: '9'
            value: 9
      - identifier: table_class
        type: Select
        renderType: selectSingle
        default: ''
        dbFieldLength: 60
        items:
          - value: ''
          - value: 'striped'
          - value: 'bordered'
      - identifier: table_header_position
        type: SelectNumber
        default: 0
        items:
          - value: 0
          - value: 1
          - value: 2
      - identifier: table_tfoot
        type: Checkbox
        renderType: checkboxToggle
        default: 0
  - identifier: FluidStyledContent/Links
    type: Basic
