name: fluid-styled-content/textpic
typeName: textpic
group: default
prefixFields: false
basics:
  - FluidStyledContent/Appearance
  - FluidStyledContent/Links
  - FluidStyledContent/Categories
fields:
  - identifier: FluidStyledContent/Headers
    type: Basic
  - identifier: bodytext
    useExistingField: true
    enableRichtext: true
  - identifier: FluidStyledContent/Images
    type: Basic
