name: fluid-styled-content/image
typeName: image
group: default
prefixFields: false
basics:
  - FluidStyledContent/Appearance
  - FluidStyledContent/Categories
fields:
  - identifier: FluidStyledContent/Headers
    type: Basic
  - identifier: FluidStyledContent/Images
    type: Basic
