identifier: FluidStyledContent/GallerySettings
fields:
  - identifier: gallery_settings_palette
    type: Palette
    label: LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.gallerySettings
    fields:
      - identifier: imageorient
        useExistingField: true
        label: LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:imageorient_formlabel
      - identifier: imagecols
        useExistingField: true
        label: LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:imagecols_formlabel
