name: fluid-styled-content/menu-abstract
typeName: menu_abstract
group: menu
prefixFields: false
basics:
  - FluidStyledContent/Appearance
  - FluidStyledContent/Links
  - FluidStyledContent/Categories
fields:
  - identifier: FluidStyledContent/Headers
    type: Basic
  - identifier: pages
    useExistingField: true
